# -*- coding: utf-8 -*-
"""Portfolio Optimization Engine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/194nKyqiEP2ugyf8teOv7FJesSqZCgvMg
"""

"""
Modern Portfolio Theory (MPT) Optimization Engine
Implementation: Ledoit-Wolf Shrinkage + Mean-Variance Optimization
Note: Requires 'yfinance' for real-market data. Fallback to simulation included.
"""

# Defensive import handling to prevent ModuleNotFoundError crashes
try:
    import yfinance as yf
    YFINANCE_AVAILABLE = True
except ImportError:
    yf = None
    YFINANCE_AVAILABLE = False

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta
from scipy.optimize import minimize
from sklearn.covariance import LedoitWolf
import warnings

warnings.filterwarnings('ignore')

# Global Plotting Configuration
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 7)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False


class PortfolioDataHandler:
    """Handles data acquisition and return calculation with mock fallback."""

    def __init__(self, tickers, start_date, end_date):
        self.tickers = tickers
        self.start_date = start_date
        self.end_date = end_date
        self.prices = None
        self.returns = None

    def fetch_data(self):
        """Fetches data from Yahoo Finance or generates simulated data if library is missing."""
        print("\n" + "="*70)
        print("FETCHING DATA")
        print("="*70)

        if YFINANCE_AVAILABLE:
            return self._fetch_from_provider()
        else:
            return self._generate_mock_data()

    def _fetch_from_provider(self):
        print(f"Downloading {len(self.tickers)} stocks from Yahoo Finance...")
        try:
            data = yf.download(
                self.tickers,
                start=self.start_date,
                end=self.end_date,
                progress=False
            )
            if data.empty:
                return self._generate_mock_data()

            if len(self.tickers) > 1:
                self.prices = data['Adj Close'] if 'Adj Close' in data.columns else data.xs('Adj Close', axis=1, level=0)
            else:
                self.prices = data[['Adj Close']]
                self.prices.columns = self.tickers

            self.prices = self.prices.ffill().bfill().dropna()
            self.returns = np.log(self.prices / self.prices.shift(1)).dropna()
            print(f"Data synchronized. Observations: {len(self.prices)}")
            return self.prices, self.returns
        except Exception as e:
            print(f"Provider Error: {e}. Falling back to simulation.")
            return self._generate_mock_data()

    def _generate_mock_data(self):
        """Generates high-fidelity synthetic data with realistic sector correlations."""
        print("ENVIRONMENT NOTICE: 'yfinance' build failed or missing.")
        print("Switching to High-Fidelity Market Simulation (GBM + Correlation)...")

        np.random.seed(42)
        days = (self.end_date - self.start_date).days
        date_rng = pd.date_range(start=self.start_date, periods=days, freq='B')
        n_days = len(date_rng)

        # Create a correlation structure (Market Factor + Idiosyncratic Noise)
        market_return = np.random.normal(0.0005, 0.012, n_days) # 0.05% daily drift

        mock_data = {}
        for ticker in self.tickers:
            # Random beta to market (0.7 to 1.5)
            beta = np.random.uniform(0.7, 1.5)
            # Individual stock noise
            noise = np.random.normal(0, 0.015, n_days)
            # Combined log returns
            stock_returns = (beta * market_return) + noise
            # Convert to price path starting at 100
            price_path = 100 * np.exp(np.cumsum(stock_returns))
            mock_data[ticker] = price_path

        self.prices = pd.DataFrame(mock_data, index=date_rng)
        self.returns = np.log(self.prices / self.prices.shift(1)).dropna()
        print(f"✓ Simulation Engine Ready. Observations: {len(self.prices)}")
        return self.prices, self.returns

    def get_summary_stats(self):
        stats = pd.DataFrame({
            'Ann. Return': self.returns.mean() * 252,
            'Ann. Volatility': self.returns.std() * np.sqrt(252),
            'Sharpe Ratio': (self.returns.mean() * 252) / (self.returns.std() * np.sqrt(252))
        })
        return stats.round(4)


class CovarianceEstimator:
    """Estimates stable covariance matrices."""

    def __init__(self, returns):
        self.returns = returns

    def ledoit_wolf_shrinkage(self):
        print("\n" + "="*70)
        print("COVARIANCE ESTIMATION")
        print("="*70)
        lw = LedoitWolf()
        lw.fit(self.returns)
        S = pd.DataFrame(lw.covariance_, index=self.returns.columns, columns=self.returns.columns)
        print(f"Ledoit-Wolf estimation complete. Intensity: {lw.shrinkage_:.4f}")
        return S


class PortfolioOptimizer:
    """Solves Mean-Variance optimization."""

    def __init__(self, returns, cov_matrix, risk_free_rate=0.065):
        self.returns = returns
        self.mu = returns.mean() * 252
        self.S = cov_matrix * 252
        self.risk_free_rate = risk_free_rate
        self.n_assets = len(returns.columns)

    def _get_metrics(self, weights):
        w = np.array(weights)
        ret = np.dot(w, self.mu)
        vol = np.sqrt(np.dot(w.T, np.dot(self.S, w)))
        sharpe = (ret - self.risk_free_rate) / vol if vol != 0 else 0
        return ret, vol, sharpe

    def _neg_sharpe(self, weights):
        return -self._get_metrics(weights)[2]

    def _port_vol(self, weights):
        return self._get_metrics(weights)[1]

    def optimize(self, criterion='sharpe'):
        crit_label = "Maximum Sharpe Ratio" if criterion == 'sharpe' else "Minimum Volatility"
        print(f"Optimizing for {crit_label}...")

        constraints = ({'type': 'eq', 'fun': lambda w: np.sum(w) - 1})
        bounds = tuple((0, 1) for _ in range(self.n_assets))
        init_w = np.array([1/self.n_assets] * self.n_assets)
        target = self._neg_sharpe if criterion == 'sharpe' else self._port_vol

        result = minimize(target, init_w, method='SLSQP', bounds=bounds, constraints=constraints)

        if result.success:
            print("✓ Optimization complete")

        weights = dict(zip(self.returns.columns, result.x))
        metrics = self._get_metrics(result.x)
        return weights, metrics

    def display_results(self, weights, metrics, title):
        """Prints results in the specific formatted style requested."""
        print("\n" + "="*70)
        print(title.upper())
        print("="*70)

        print("\nPortfolio Allocation:")
        print("-" * 40)

        # Sort weights by value for better readability
        sorted_weights = sorted(weights.items(), key=lambda x: x[1], reverse=True)
        for ticker, weight in sorted_weights:
            if weight > 0.0001:  # Only show non-zero weights
                clean_ticker = ticker.replace('.NS', '')
                print(f" {clean_ticker:15} : {weight:7.2%}")

        print("-" * 40)
        print("\nPerformance Metrics:")
        print(f" Expected Annual Return:   {metrics[0]:7.2%}")
        print(f" Annual Volatility:        {metrics[1]:7.2%}")
        print(f" Sharpe Ratio:             {metrics[2]:7.2f}")
        print("="*70)

    def generate_frontier(self, points=20):
        print("\n" + "="*70)
        print("EFFICIENT FRONTIER")
        print("="*70)
        print(f"Computing {points} frontier points...")

        min_ret, max_ret = self.mu.min(), self.mu.max()
        target_range = np.linspace(min_ret, max_ret, points)

        frontier_vols = []
        for target in target_range:
            cons = [{'type': 'eq', 'fun': lambda w: np.sum(w) - 1},
                    {'type': 'eq', 'fun': lambda w: np.dot(w, self.mu) - target}]
            res = minimize(self._port_vol, [1/self.n_assets]*self.n_assets,
                           method='SLSQP', bounds=tuple((0, 1) for _ in range(self.n_assets)),
                           constraints=cons)
            frontier_vols.append(self._get_metrics(res.x)[1] if res.success else None)

        plt.figure()
        plt.plot(frontier_vols, target_range, 'k--', alpha=0.4, label='Efficient Frontier')
        w_s, p_s = self.optimize('sharpe')
        w_v, p_v = self.optimize('vol')
        plt.scatter(p_s[1], p_s[0], marker='*', s=200, c='red', label='Max Sharpe')
        plt.scatter(p_v[1], p_v[0], marker='*', s=200, c='blue', label='Min Volatility')

        for i, ticker in enumerate(self.returns.columns):
            plt.scatter(np.sqrt(self.S.iloc[i, i]), self.mu.iloc[i], alpha=0.5)
            plt.annotate(ticker.split('.')[0], (np.sqrt(self.S.iloc[i, i]), self.mu.iloc[i]))

        plt.title('Portfolio Optimization Analysis')
        plt.xlabel('Annualized Volatility (Risk)')
        plt.ylabel('Annualized Return')
        plt.legend()
        plt.tight_layout()
        plt.savefig('efficient_frontier.png', dpi=300, bbox_inches='tight')
        plt.show()


def main():
    print("\n" + "="*70)
    print("MODERN PORTFOLIO THEORY IMPLEMENTATION")
    print("="*70)

    # Selection of NIFTY Bluechips
    assets = ['TCS.NS', 'INFY.NS', 'RELIANCE.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'ITC.NS', 'HINDUNILVR.NS']
    end = datetime.now()
    start = end - timedelta(days=3*365)

    try:
        handler = PortfolioDataHandler(assets, start, end)
        _, returns = handler.fetch_data()

        print("\n" + "="*70)
        print("SUMMARY STATISTICS")
        print("="*70)
        print(handler.get_summary_stats())

        estimator = CovarianceEstimator(returns)
        S = estimator.ledoit_wolf_shrinkage()

        print("\n" + "="*70)
        print("PORTFOLIO OPTIMIZATION")
        print("="*70)

        optimizer = PortfolioOptimizer(returns, S)

        # Max Sharpe Optimization
        w_max, p_max = optimizer.optimize('sharpe')
        optimizer.display_results(w_max, p_max, "Maximum Sharpe Ratio Portfolio")

        # Min Volatility Optimization
        w_min, p_min = optimizer.optimize('vol')
        optimizer.display_results(w_min, p_min, "Minimum Volatility Portfolio")

        # Frontier Visualization
        optimizer.generate_frontier()

        print("\n" + "="*70)
        print("ANALYSIS COMPLETE")
        print("="*70)

    except Exception as e:
        print(f"\nEngine Failure: {e}")

if __name__ == "__main__":
    main()